SaltySurf/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Brand, Surfboard, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db

main_bp = Blueprint('main', __name__)

# Homepage
@main_bp.route('/')
def index():
    brands = db.session.scalars(db.select(Brand).order_by(Brand.id))
    return render_template('index.html', brands=brands)

# View all surfboards
@main_bp.route('/surfboard/<int:brandid>')
def brandsurfboard(brandid):
    surfboard = db.session.scalars(db.select(Surfboard).where(Surfboard.brand_id==brandid))
    return render_template('brandsurfboard.html', surfboard=surfboard)

# Referred to as "Basket" to the user
@main_bp.route('/order', methods=['POST','GET'])
def order():
    surfboard_id = request.values.get('surfboard_id')
    print(f'Values: {surfboard_id}')
    # retrieve order if there is one
    if 'order_id'in session.keys():
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status = False, firstname='', surname='', email='', phone='', address='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None
    
    # calcultate totalprice
    total_price = 0
    if order is not None:
        for surfboard in order.surfboard:
            total_price = total_price + surfboard.price
    
    # Are we adding an item?
    if surfboard_id is not None and order is not None:
        surfboard = db.session.scalar(db.select(Surfboard).where(Surfboard.id==surfboard_id))
        try:
            order.surfboard.append(surfboard)
            for surfboard in order.surfboard:
                total_price += surfboard.price
            order.total_cost = total_price
            db.session.commit()
        except:
            flash('There was an issue adding the item to your basket', category='danger')
        return redirect(url_for('main.order'))
    return render_template('order.html', order=order, total_price=total_price)

@main_bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    print(f'Surfboard to delete ID is: {id}')
    if 'order_id' in session:
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        if not order:
            flash("There's no order to delete!")
            return redirect(request.referrer)
        print(order.surfboard)
        surfboard_to_delete = db.session.scalar(db.select(Surfboard).where(Surfboard.id==id))
        print(f'Deleting: {surfboard_to_delete.name}')
        try:
            surfboard_to_delete.qty = 0
            order.surfboard.remove(surfboard_to_delete)
            db.session.commit()
        except:
            print('Something went wrong when trying to delete the order')
        
    return redirect(url_for('main.order'))

# Empty basket
@main_bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        for surfboard in surfboard.surfboard:
            order.surfboard.remove(surfboard)
        session.pop('order_id')
        db.session.commit()
        flash('Basket emptied!')
    else:
        flash("There's no order to delete!")
        return redirect(request.referrer)
    return redirect(url_for('main.index'))

# Complete the order
@main_bp.route('/checkout', methods=['GET', 'POST'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        if not order.surfboard:
            flash('You need to add a surfboard to your basket first!')
            return(redirect(request.referrer))
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.address = form.address.data
            order.phone = form.phone.data
            totalcost = 0
            for surfboard in order.surfboard:
                totalcost = totalcost + surfboard.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you for your order! Tracking details were sent to the email address provided!')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form)

# Search functionality
@main_bp.route("/search", methods=['GET','POST'])
def search():
    search = request.args.get('search')
    search = '%{}%'.format(search)
    surfboards = Surfboard.query.filter(Surfboard.description.like(search)).all()
    return render_template('brandsurfboard.html', surfboard=surfboards)

SaltySurf/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Salty Surf</title>
    <meta name="Salty Surf" content="Salty Surf">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <style>
        .my-row {
            border: 1px solid grey;
        }

        header {
            background-color: #343a40;
            padding: 1.5rem 0;
        }

        .navbar-brand {
            font-weight: bold;
            font-size: 1.5rem;
        }

        .navbar-brand img {
            width: 40px; /* Increase the logo size */
            height: 40px;
            margin-right: 15px;
        }

        .navbar-light .form-inline {
            margin-left: auto;
        }

        .navbar-light .form-inline input {
            border-radius: 3rem;
            padding: 0.25rem 0.5rem;
            font-size: 0.875rem;
            border: none;
            box-shadow: none;
        }

        .navbar-light .form-inline button {
            border-radius: 3rem;
            padding: 0.25rem 0.5rem;
            font-size: 0.875rem;
            border: none;
            box-shadow: none;
            background-color: #fff;
            color: #343a40;
        }
        
        footer {
            background-color: #343a40;
            padding: 1.5rem 0;
            color: #fff;
        }

        footer p {
            margin-bottom: 0;
        }


    </style>
</head>

<body class="bg-dark">

    <!-- putting header inside container will prevent full width navbar -->

    <header>

        <!--navbar creates a navigation bar -->
        <!-- Colours https://getbootstrap.com/docs/4.0/utilities/colors/ -->

        <nav class="navbar navbar-expand-lg navbar-light bg-dark">

            <a class="navbar-brand text-light" href="{{ url_for('main.index') }}">
                <img src="{{url_for('static', filename='img/saltysurflogo.png')}}" class="d-inline-block align-top"
                    alt="Salty Surf Logo">
                <span style="font-family: 'Pacifico', cursive;">Salty Surf</span>
            </a>

            <!-- create a button for collapsing the menu -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">

                <!-- Tutor Anshul Inspired -->
                <a class="nav-item nav-link text-light" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">About</a>
                
                <!--Basket Link-->
                <a class="nav-item nav-link text-light" href="{{url_for('main.order')}}">Basket</a>

                <!-- this link will fail but good test of the 404 handler -->
                <a class="nav-item nav-link text-light" href="discounts.html">Offers</a>

                <!-- right aligned menu items thanks to ml-auto -->
                <ul class="nav navbar-nav ml-auto">

                    <li class="nav-item">
                        
                <!-- search box -->

                        <form class="form-inline my-2 my-lg-0 ml-5" action="{{url_for('main.search')}}">

                            <input class="form-control" type="search" placeholder="Search" aria-label="Search" name = "search">
                            <button class="btn btn-outline-black btn btn-secondary btn-s my-0 ml-1"
                            type="submit">Search</button>
    
                        </form>
                    </li>
                </ul>

        </nav>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-primary" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
            </div>
        {% endif %}
        {% endwith %} 

        {% block head %}
        
        {% endblock %}

    </header>


    <!-- main page content goes in container -->
    <div class="container-fluid">
        <main>
            {% block main %}
            
            {% endblock %}
        </main>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container text-center">
            <p>Copyright &copy; Salty Surf</p>
        </div>
    </footer>
    <!-- Footer -->


    <!-- jQuery first, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

</body>

</html>
<!---->

SaltySurf/templates/brandsurfboard.html
{% extends 'base.html' %}

{% block main %}
<section>

    <div class="text-white text-center">
        <div>
            <p></p>
            <p class="h3 text-white mb-4">Browse our wide selection of surboards!</p>
        </div>
    </div>

    <div class="card-columns">
        <!-- each tour is a bootstrap card -->
        {% for surfboard in surfboard%}
        <div class="card-wrapper">
        <div class="card">
            <img class="card-img-top" src="{{ url_for('static', filename='img/'+surfboard.image) }}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title">{{ surfboard.name }}</h4>
                <p class="card-text">{{ surfboard.description }}</p>
                {% if surfboard.boardlevel == 'Beginner'%}
                <span class="badge badge-primary">{{surfboard.boardlevel}}</span>
                {% endif %}
                {% if surfboard.boardlevel == 'Intermediate'%}
                <span class="badge badge-warning">{{surfboard.boardlevel}}</span>
                {% endif %}
                {% if surfboard.boardlevel == 'Expert'%}
                <span class="badge badge-danger">{{surfboard.boardlevel}}</span>
                {% endif %}
            </div>
            <div class="card-footer">
                <form action="{{ url_for('main.order') }}">
                    <input type="hidden" id="surfboard_id" name="surfboard_id" value="{{ surfboard.id }}">
                    <input class="btn btn-secondary" type="submit" value="Add to Basket">
                </form>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
    
    <style>
    .card-columns {
      background-color: #343a40;
    }
    
    .card {
      border: 2px solid;
      border-image-slice: 1;
      border-width: 5px;
      border-image-source: linear-gradient(to right, #C2DFFF, #FFE1C2);
      border-radius: 5px;
      margin: 10px;
    }
    </style>

</section>
{% endblock %}


SaltySurf/templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap4/form.html" as wtf %}

{% block main %}
    <section>  
        <div class="container text-white">
            <div class="row">
                <div class = "col-12">
                    <h1>Checkout</h1>
                    <p>
                        You're halfway to shredding! Finalise your details and your board will be on the way. Thank you! 
                    </p>
                </div>
            </div>
            <div class="row">
                <div class = "col-6">
                    {{ wtf.render_form(form) }}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

SaltySurf/templates/error.html
{% extends 'base.html' %}

{% block main %}
<div class="container text-white">
    <h1>Error</h1>
    <p>Sorry, but something went wrong!</p>
    <p>More info: {{error}}</p>
</div>
{% endblock %}

SaltySurf/templates/index.html
{% extends 'base.html' %}

{% block head %}
<!-- Add a big banner to welcome user -->
<div class="jumbotron jumbotron-fluid card card-image" style="background-image: url({{url_for('static', filename='img/background.jpg')}}); background-size: cover; height: 100vh;">
    <div class="text-black text-center py-5 px-4">
        <div>
            <h1 class="display-3 font-weight-bold">Salty Surf Shop</h1>
            <p class="lead text-dark">The worst day of surfing is better than the best day at work!</p>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<style>
#product-carousel {
  border: 5px solid black;
}

.carousel-inner {
  max-height: 500px;
  overflow: hidden;
}

.carousel-inner img {
  object-fit: cover;
  height: 100%;
  width: 100%;
}



</style>

<section class="bg-dark py-5">
    <div class="container">
        <div class="text-center mb-4">
            <h2 class="display-4 font-weight-bold text-white">Athlete Spotlight</h2>
        </div>
    </div>
</section>

<!-- Product carousel container -->
<section class="bg-transparent py-5">
<div id="product-carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#product-carousel" data-slide-to="0" class="active"></li>
      <li data-target="#product-carousel" data-slide-to="1"></li>
      <li data-target="#product-carousel" data-slide-to="2"></li>
    </ol>
  
    <!-- Carousel inner -->
    <div class="carousel-inner">
      <div class="carousel-item active">
        <!-- Product 1 content -->
        <img src="\static\img\billabong3.jpg" alt="Athlete 1" class="img-fluid">
      </div>
      <div class="carousel-item">
        <!-- Product 2 content -->
        <img src="\static\img\athlete3.jpg" alt="Athlete 2" class="img-fluid">
      </div>
      <div class="carousel-item">
        <!-- Product 3 content -->
        <img src="\static\img\athlete1.jpg" alt="Athlete 3" class="img-fluid">
      </div>
    </div>
  
    <!-- Controls -->
    <a class="carousel-control-prev" href="#product-carousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#product-carousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
</section>
<!-- Display the surfboards to the user -->
<section class="bg-dark py-5">
    <div class="container">
        <div class="text-center mb-4">
            <h2 class="display-4 text-white">Choose one of the three top Surfboard brands:</h2>
        </div>
        <div class="card-deck">
            {% for brand in brands %}
            <div class="card mb-4 border border-dark">
                <img class="card-img-top" src="{{ url_for('static', filename='img/'+brand.image) }}" alt="Card image">
                <div class="card-body">
                    <h4 class="card-title">{{brand.name}}</h4>
                    <p class="card-text">{{brand.description}}</p>
                </div>
                <div class="card-footer">
                    <a href="{{url_for('main.brandsurfboard', brandid=brand.id) }}" class="btn btn-secondary">Surfboards</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

SaltySurf/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>  
    <div class="container">
        <div class="row co-12 d-flex mt-2 mb-2">
            <h3 class="text-white">Shopping Basket</h3>
        </div>
        <!-- each tour on seperate row -->
        {% for surfboard in order.surfboard %}
            <div class="row shadow-md my-row mb-3">
                <div class="col-sm-10 card">
                    <h5 class="card-header"> : {{ surfboard.Brand.name }} {{ surfboard.name }}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <img class="img-thumbnail" src="{{ url_for('static', filename=('img/' + surfboard.image)) }}">
                            </div>
                            <div class="col-10">
                                <!-- Item Description -->
                                <p class="card-text">{{ surfboard.description }}</p>   
                            </div>  
                        </div>                      
                    </div>
                </div>
                <br><br>
                <!-- right column has price and delete button -->
                <div class="col-sm-2">
                    <!-- delete item button -->
                        <h5 class = "text-white">{{ "$%.2f"|format(surfboard.price) }}</h5>
                        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                            <input type="hidden" id="id" name="id" value="{{surfboard.id}}">
                            <input type="submit" value="Delete" class="btn btn-secondary mb-3">
                        </form> 
                </div>
            </div>
        {% endfor %}
        
        <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex">
                <h5 class="mt-4 text-white">Total : {{ "$%.2f"|format(total_price) }}</h5>
            </div>
        
            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="{{ url_for('main.index', _anchor='brands_anchor') }}" class="btn btn-secondary mr-4">Brands</a>
                <a href="{{ url_for('main.checkout') }}" class="btn btn-secondary mr-4">Checkout</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-secondary">Empty Basket</a>
            </div>
        </section>
    </div>
</section>
{% endblock %}